interpreters: 
  velocity_interpreter_node:
    max_vel: 1.6

calculators:
  file_prefix: "test1_rosylernt" # Prepended to all savefiles and rosbags
  robot_has_stopped_node: # node name 
    param: 0.0
    tolerance: 0.01

  robot_has_max_vel: # node name
    param: 1.6         # This value decides at which velocity (X axis) the runner triggers stop signal
    tolerance: 0.01

  bag_video:
    dest_dir: /home/tejas/araig/bags
    topics:
      - /amcl/parameter_descriptions
      - /amcl/parameter_updates
      - /amcl_pose
      - /analog_sensors
      - /areas_updated
      - /arrows_updated
      - /base/driver/parameter_descriptions
      - /base/driver/parameter_updates
      - /base/force_for_gui
      - /base/fts_adaptive_force_controller/FTSAdaptiveForceController/parameter_descriptions
      - /base/fts_adaptive_force_controller/FTSAdaptiveForceController/parameter_updates
      - /base/fts_adaptive_force_controller/FTSBaseController/parameter_descriptions
      - /base/fts_adaptive_force_controller/FTSBaseController/parameter_updates
      - /base/fts_adaptive_force_controller/PassiveBehaviorControllerBase/parameter_descriptions
      - /base/fts_adaptive_force_controller/PassiveBehaviorControllerBase/parameter_updates
      - /base/fts_adaptive_force_controller/adapted_limited_input_force
      - /base/fts_adaptive_force_controller/adaption/maxFT
      - /base/fts_adaptive_force_controller/adaption/scaled_value
      - /base/fts_adaptive_force_controller/debug/admittance_velocity
      - /base/fts_adaptive_force_controller/debug/after_cor_modality
      - /base/fts_adaptive_force_controller/debug/after_counterforce_modality
      - /base/fts_adaptive_force_controller/debug/force_input_raw
      - /base/fts_adaptive_force_controller/debug/force_input_scaled_limited
      - /base/fts_adaptive_force_controller/debug/platform_hw_velocity
      - /base/fts_adaptive_force_controller/debug/velocity_output
      - /base/fts_adaptive_force_controller/parametrization/adaptX/currentScale
      - /base/fts_adaptive_force_controller/parametrization/adaptX/distanceDiffToLast
      - /base/fts_adaptive_force_controller/parametrization/adaptX/maxVelFactor
      - /base/fts_adaptive_force_controller/parametrization/adaptX/minVelFactor
      - /base/fts_adaptive_force_controller/parametrization/base/averageDist
      - /base/fts_adaptive_force_controller/parametrization/base/currentDistanceFromStart
      - /base/fts_adaptive_force_controller/parametrization/base/currentRawForce
      - /base/fts_adaptive_force_controller/parametrization/base/resultingForce
      - /base/fts_adaptive_force_controller/parametrization/base/virtualSpringForce
      - /base/fts_adaptive_force_controller/parametrization/max_force_result
      - /base/fts_adaptive_force_controller/passive_AdaptionFactor
      - /base/fts_adaptive_force_controller/passive_ChuyIntegral3d
      - /base/fts_adaptive_force_controller/passive_RealInputforce
      - /base/fts_adaptive_force_controller/passive_SlidingIntegralVal
      - /base/fts_adaptive_force_controller/passive_SlidingIntegralVal3d
      - /base/joint_states
      - /base/odometry_controller/odometry
      - /base/output_data
      - /base/twist_controller/bl_caster_rotation_joint/parameter_descriptions
      - /base/twist_controller/bl_caster_rotation_joint/parameter_updates
      - /base/twist_controller/br_caster_rotation_joint/parameter_descriptions
      - /base/twist_controller/br_caster_rotation_joint/parameter_updates
      - /base/twist_controller/command
      - /base/twist_controller/default/steer_ctrl/parameter_descriptions
      - /base/twist_controller/default/steer_ctrl/parameter_updates
      - /base/twist_controller/f_caster_rotation_joint/parameter_descriptions
      - /base/twist_controller/f_caster_rotation_joint/parameter_updates
      - /base/twist_controller/wheel_commands
      - /base/twist_mux/command_navigation
      - /base/twist_mux/command_safe
      - /base/twist_mux/command_script_server
      - /base/twist_mux/command_syncmm
      - /base/twist_mux/command_teleop_android
      - /base/twist_mux/command_teleop_joy
      - /base/twist_mux/command_teleop_keyboard
      - /base/twist_mux/locks/pause_all
      - /base/twist_mux/locks/pause_navigation
      - /base/twist_mux/locks/pause_teleop
      - /base/twist_mux/marker
      - /base/velocity_smoother/command
      - /base/velocity_smoother/parameter_descriptions
      - /base/velocity_smoother/parameter_updates
      - /base/virtual_areas/counterforce/center_dist_percent
      - /base/virtual_forces/modalities_debug/resulting_force
      - /base/virtual_forces/modalities_debug/resulting_velocity
      - /base/virtual_forces/modalities_debug/velocity_in
      - /base/virtual_forces/modalities_debug/velocity_out
      - /base/virtual_forces/virtual_forces/modalities_debug/position
      - /base/wheel_controller/bl_caster_rotation_joint/parameter_descriptions
      - /base/wheel_controller/bl_caster_rotation_joint/parameter_updates
      - /base/wheel_controller/br_caster_rotation_joint/parameter_descriptions
      - /base/wheel_controller/br_caster_rotation_joint/parameter_updates
      - /base/wheel_controller/default/steer_ctrl/parameter_descriptions
      - /base/wheel_controller/default/steer_ctrl/parameter_updates
      - /base/wheel_controller/f_caster_rotation_joint/parameter_descriptions
      - /base/wheel_controller/f_caster_rotation_joint/parameter_updates
      - /base/wheel_controller/wheel_commands
      - /base_laser_back/extended_laser_scan
      - /base_laser_back/laser_back/parameter_descriptions
      - /base_laser_back/laser_back/parameter_updates
      - /base_laser_back/output_paths
      - /base_laser_back/raw_data
      - /base_laser_back/scan
      - /base_laser_left/extended_laser_scan
      - /base_laser_left/laser_left/parameter_descriptions
      - /base_laser_left/laser_left/parameter_updates
      - /base_laser_left/output_paths
      - /base_laser_left/raw_data
      - /base_laser_left/scan
      - /base_laser_right/extended_laser_scan
      - /base_laser_right/laser_right/parameter_descriptions
      - /base_laser_right/laser_right/parameter_updates
      - /base_laser_right/output_paths
      - /base_laser_right/raw_data
      - /base_laser_right/scan
      - /begin_write
      - /clicked_point
      - /dashboard_agg
      - /data/calc/displacement/angular
      - /data/calc/displacement/position
      - /data/interpreter/location/obstacle
      - /data/interpreter/location/robot
      - /data/robot/twist/linear/x
      - /diagnostics
      - /diagnostics_agg
      - /diagnostics_toplevel_state
      - /digital_sensors
      - /docker_control/dock/cancel
      - /docker_control/dock/feedback
      - /docker_control/dock/goal
      - /docker_control/dock/result
      - /docker_control/dock/status
      - /docker_control/undock/cancel
      - /docker_control/undock/feedback
      - /docker_control/undock/goal
      - /docker_control/undock/result
      - /docker_control/undock/status
      - /emergency_stop_state
      - /hedge_pos_a
      - /image_view/output
      - /image_view/parameter_descriptions
      - /image_view/parameter_updates
      - /image_view2/output
      - /image_view2/parameter_descriptions
      - /image_view2/parameter_updates
      - /initialpose
      - /joint_states
      - /joy
      - /joy/set_feedback
      - /leds_rectangle/blinky/cancel
      - /leds_rectangle/blinky/feedback
      - /leds_rectangle/blinky/goal
      - /leds_rectangle/blinky/result
      - /leds_rectangle/blinky/status
      - /leds_rectangle/chaser_light/cancel
      - /leds_rectangle/chaser_light/feedback
      - /leds_rectangle/chaser_light/goal
      - /leds_rectangle/chaser_light/result
      - /leds_rectangle/chaser_light/status
      - /leds_rectangle/four_regions/cancel
      - /leds_rectangle/four_regions/feedback
      - /leds_rectangle/four_regions/goal
      - /leds_rectangle/four_regions/result
      - /leds_rectangle/four_regions/status
      - /leds_rectangle/led_force
      - /leds_rectangle/led_force_with_color
      - /leds_rectangle/led_setLeds
      - /leds_rectangle/led_setRange
      - /leds_rectangle/police/cancel
      - /leds_rectangle/police/feedback
      - /leds_rectangle/police/goal
      - /leds_rectangle/police/result
      - /leds_rectangle/police/status
      - /leg_detection/body_center_stamped
      - /leg_detection/cov_ellipses
      - /leg_detection/legs_and_vel_direction
      - /leg_detection/line_strip
      - /leg_detection/people
      - /leg_detection/people_msg_stamped
      - /leg_detection/posXY_velXY_accXY_lId_pId_conf_fst_leg
      - /leg_detection/posXY_velXY_accXY_lId_pId_conf_snd_leg
      - /leg_detection/tracking_area
      - /leg_detection/tracking_zones
      - /map
      - /map_metadata
      - /map_updates
      - /mobile_robot_pose
      - /mobile_robot_position
      - /modalities/modalitiesVFController/parameter_descriptions
      - /modalities/modalitiesVFController/parameter_updates
      - /modalities/virtual_forces/parameter_descriptions
      - /modalities/virtual_forces/parameter_updates
      - /move_base/global_costmap/costmap
      - /move_base_simple/goal
      - /particlecloud
      - /path_updated
      - /power_board/current
      - /power_board/voltage
      - /power_state
      - /record_info_topic
      - /robotrainer/editor/feedback
      - /robotrainer/editor/update
      - /robotrainer/editor/update_full
      - /robotrainer/parameter_descriptions
      - /robotrainer/parameter_updates
      - /robotrainer_deviation/current_path_index
      - /robotrainer_deviation/robotrainer_deviation
      - /robotrainer_deviation/robotrainer_deviation_markers
      - /robotrainer_hw/joint_states
      - /robotrainer_user_study_manager/parameter_descriptions
      - /robotrainer_user_study_manager/parameter_updates
      - /robotrainer_user_study_manager/study_status
      - /rosout
      - /rosout_agg
      - /rt2_sca_sync_node/sync_signal
      - /scan_unified
      - /script_server/cancel
      - /script_server/feedback
      - /script_server/goal
      - /script_server/result
      - /script_server/state
      - /script_server/status
      - /sensor_usb_cam/camera_info
      - /sensor_usb_cam/image_raw
      - /sensor_usb_cam/image_raw/theora
      - /sensor_usb_cam/image_raw/theora/parameter_descriptions
      - /sensor_usb_cam/image_raw/theora/parameter_updates
      - /sensor_usb_cam2/camera_info
      - /sensor_usb_cam2/image_raw
      - /sensor_usb_cam2/image_raw/theora
      - /sensor_usb_cam2/image_raw/theora/parameter_descriptions
      - /sensor_usb_cam2/image_raw/theora/parameter_updates
      - /set_digital_sensor
      - /signal/calc/robot_has_stopped
      - /signal/calc/robot_in_collision
      - /signal/calc/robot_reached_goal_and_stopped
      - /signal/robot/emergency
      - /signal/runner/start_robot
      - /signal/runner/stop_robot
      - /signal/runner/test_completed
      - /signal/runner/test_failed
      - /signal/runner/test_succeeded
      - /signal/ui/abort_test
      - /signal/ui/interrupt_test
      - /signal/ui/start_test
      - /sound/say/cancel
      - /sound/say/feedback
      - /sound/say/goal
      - /sound/say/result
      - /sound/say/status
      - /statistics
      - /teleop/set_light/cancel
      - /teleop/set_light/feedback
      - /teleop/set_light/goal
      - /teleop/set_light/result
      - /teleop/set_light/status
      - /tf
      - /tf_static
      - /walls_updated