runner:
  timeout_check_goal: 2
  timeout_after_complete: 3
  timeout_after_interrupt_collision: 15
  
interpreters: 
  goal:
    frame_id: map
    child_frame_id: goal
    position:
      x: -0.26
      y: -1.88
      z: 0
    yaw: 0 # degree
  goal_action: move_base # if "None", won't use action
  wait_action: 5 # time for waiting for action available
  rate: 100

calculators:
  dest_dir: ""
  robot_type: "cob"
  test_type: "test5_with_nav_dynamic"

  robot_in_collision_node: # node name
    pose_tolerance: 0.5 # Threshold for pose (meter)
    orientation_tolerance: None # Threshold for orientation (Quaternion, radian) for goal pose

  robot_has_stopped_node: # node name 
    param: 0.0
    tolerance: 0.005

  robot_reached_goal_node: # node name
    pose_tolerance: 0.05
    orientation_tolerance: None
  
  goal_and_stop_node: # node name
    tolerance: 0 

  goal_time_node:
    if_log: True

  param_logger_node:
    start_offset: 1
    stop_offset: 0.5
    namespaces: 
      - "runner"
      - "interpreters"
      - "calculators"
  
  results_logger_node:
    start_offset: 0.5
    stop_offset: 0.1
    logginng_topics: 
      - /data/calc/goal_time

  folder_bagger_node:
    start_offset: 1 # sleep after creating folder
    stop_offset: 2 # sleep before killing
    blacklist:
      - compressed
      - torso
      - mimic
      - bms
      - collision_velocity_filter
      - arm
      - light 
      - docker
      - dashboard_agg
      - gripper
      - sound
      - base
      - script_server
      - map
      - scan
      - sensorring
      - image_view