save_filename: "test5" # Prepended to all savefiles and rosbags

# test_runner:

interpreters: 
  goal_interpreter_node: # node name 
    goal:
      frame_id: map
      position:
        x: 1.5
        y: 0.4
        z: 0
      yaw: 90
  velocity_interpreter_node: # node name 
    max_vel: 5
    zero_vel: 0 # The velocity that is defined as Zero for recognising robot stop

calculators:
  robot_has_stopped_node: # node name 
    param: 0.0
    tolerance: 0.01

  robot_in_collision_node: # node name
    pose_tolerance: 0.5 # Threshold for pose (meter)
    orientation_tolerance: None # Threshold for orientation (Quaternion, radian) for goal pose

  robot_reached_goal_node: # node name
    pose_tolerance: 0.05
    orientation_tolerance: None
  
  goal_and_stop_node: # node name
    tolerance: 0 

  bag_video:
    topics: # Must be fully resolved namespaces. Records these topics.
      - /signal/runner/enable_robot
      - /signal/runner/test_succeeded
      - /signal/runner/test_failed
      - /signal/runner/test_completed
      - /signal/ui/start_test
      - /signal/ui/stop_test
      - /signal/ui/abort_test
      - /signal/calc/robot_in_collision
      - /signal/calc/robot_reached_goal_and_stop
    dest_dir: "/home/tejas/araig/bags" # Full path required. Saves bags here.
  file_prefix: test