runner:
  start_logging_offset: 10
  stabilization_timeout: 0.25
  acceleration_timeout: 2
  verification_timeout: 0.25
  decceleration_timeout: 2
    
interpreters:
  velocity_interpreter_node: 
    max_vel: 0.25
    rate: 100

calculators:
  robot_type: "mobika"
  test_type: "test1_braking"

  robot_reached_max_vel_node: 
    param: 0.25
    tolerance: 0.06
  
  robot_has_stopped_node:
    param: 0.0
    tolerance: 0.001

  braking_time_node:
    if_log: True

  param_logger_node:
    start_offset: 0.5
    stop_offset: 0.5
    namespaces: 
      - "runner"
      - "interpreters"
      - "calculators"
  
  results_logger_node:
    start_offset: 0.5
    stop_offset: 0.1
    logginng_topics: 
      - /data/calc/braking_time
      - /data/calc/braking_distance

  folder_bagger_node:
    start_offset: 2 # Wait these many seconds before killing
    stop_offset: 2 # Wait these many seconds before killing
    whitelist:
    # Default whitelist: ["/signal/", "/data", "usb_cam", "/tf"]
    # Any topics which have one of these STRINGS in them will be added to the whitelist for recording,
      - hedge
      - ros
    blacklist:
    # Any WHITELISTED topics which have one of these STRINGS in them will be rejected for recording
      - compressed

  robot_speed_logger:
    start_offset: 1.5 # Must be longer than folder bagger, since this tends to be created first.
    stop_offset: 0.1
    logged_data_title: "robot_speed" # Used to name the file
    column_headers: ["Time", "Speed"]