runner:
  start_logging_offset: 2
  verification_timeout: 0.25
  goal_reach_timeout: 18
   
interpreters: 
  goal:
    frame_id: map
    child_frame_id: goal
    position:
      x: -0.26
      y: -1.88
      z: 0
    yaw: 1.57 # degree
  goal_action: move_base # if "None", won't use action
  wait_action: 5 # time for waiting for action available
  rate: 100

  obstacle_tf2_broadcaster_node:
    goal:
      child_frame_id: obstacle
      frame_id: map
      position:
        x: -1
        y: 0
        z: 0
      yaw: 1.57 # degree

calculators:
  robot_type: "mobika"
  test_type: "test5_with_nav"

  robot_has_stopped_node: # node name 
    param: 0.0
    tolerance: 0.005

  robot_in_collision_node: # node name
    pose_tolerance: 0.5 # Threshold for pose (meter)
    orientation_tolerance: None # Threshold for orientation (Quaternion, radian) for goal pose

  robot_reached_goal_node: # node name
    pose_tolerance: 0.1
    orientation_tolerance: None
  
  goal_and_stop_node: # node name
    tolerance: 0 

  goal_time_node:
    if_log: True

  param_logger_node:
    start_offset: 1
    stop_offset: 0.5
    namespaces: 
      - "runner"
      - "interpreters"
      - "calculators"
  
  results_logger_node:
    start_offset: 0.5
    stop_offset: 0.1
    logginng_topics: 
      - /data/calc/goal_time

  folder_bagger_node:
    start_offset: 2 # Wait these many seconds before killing
    stop_offset: 2 # Wait these many seconds before killing
    whitelist:
    # Default whitelist: ["/signal/", "/data", "usb_cam", "/tf"]
    # Any topics which have one of these STRINGS in them will be added to the whitelist for recording,
      - hedge
      - ros
      #- move_base
    blacklist:
    # Any WHITELISTED topics which have one of these STRINGS in them will be rejected for recording
      - compressed

  robot_pose_logger:
    start_offset: 1.5 # Must be longer than folder bagger, since this tends to be created first.
    stop_offset: 0.1
    logged_data_title: "robot_pose"
    column_headers: ["Time", "Seq",
                              "Pose.Position.x",
                              "Pose.Position.y",
                              "Pose.Position.z",
                              "Pose.Orientation.x",
                              "Pose.Orientation.y",
                              "Pose.Orientation.z",
                              "Pose.Orientation.w",
                              "Roll(deg)", "Pitch(deg)", "Yaw(deg)"]
