runner:
    timeout_after_complete: 3

interpreters:
  velocity_interpreter_node: # node name 
    max_vel: 0.3
    rate: 100

calculators:
  dest_dir: ""
  robot_type: "turtlebot3_sim"
  test_type: "test5_without_nav"

  robot_has_stopped_node: # node name 
    param: 0.0
    tolerance: 0.005

  robot_stop_gap_node:
    if_log: "true"

  robot_in_collision_node: # node name
    pose_tolerance: 0.5 # Threshold for pose (meter)
    orientation_tolerance: None # Threshold for orientation (Quaternion, radian) for goal pose
    
  folder_manager_node:
    start_offset: 0.5
    stop_offset: 4 # after offset will rename folder with test result, only can do it after rosbag closed

  param_logger_node:
    start_offset: 1
    stop_offset: 0.5
    namespaces: 
      - "runner"
      - "interpreters"
      - "calculators"
  
  results_logger_node:
    start_offset: 0.5
    stop_offset: 0.1
    logginng_topics: 
      - /data/calc/robot_stop_gap

  folder_bagger_node:
    start_offset: 1 # Wait these many seconds before strat
    stop_offset: 2 # Wait these many seconds before killing
    blacklist:
      - /sensor_usb_cam/image_raw/compressed/parameter_updates
      - /sensor_usb_cam/image_raw/compressed/parameter_descriptions
      - /sensor_usb_cam/image_raw/compressedDepth
      - /sensor_usb_cam/image_raw/compressedDepth/parameter_descriptions
      - /sensor_usb_cam/image_raw/compressedDepth/parameter_updates
      - /sensor_usb_cam/image_raw/theora
      - /sensor_usb_cam/image_raw/theora/parameter_descriptions
      - /sensor_usb_cam/image_raw/theora/parameter_updates
      - /sensor_usb_cam2/image_raw/compressed/parameter_updates
      - /sensor_usb_cam2/image_raw/compressed/parameter_descriptions
      - /sensor_usb_cam2/image_raw/compressedDepth
      - /sensor_usb_cam2/image_raw/compressedDepth/parameter_descriptions
      - /sensor_usb_cam2/image_raw/compressedDepth/parameter_updates
      - /sensor_usb_cam2/image_raw/theora
      - /sensor_usb_cam2/image_raw/theora/parameter_descriptions
      - /sensor_usb_cam2/image_raw/theora/parameter_updates
